In [1]:
# Exp no.: 5

In [2]:
#Aim: To create array using numpy

In [3]:
# Name: Gouri Pandey

In [4]:
# Roll no : 46

In [5]:
# sec: B

In [6]:
# subject: DSS ( Data science and statistics )

In [8]:
# Importing the basic Library

In [9]:
import numpy as np

In [10]:
arr1 = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr1)

1D Array: [1 2 3 4 5]


In [11]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:\n", arr2)



2D Array:
 [[1 2 3]
 [4 5 6]]


In [12]:
rand_arr = np.random.rand(2, 2)
print("\nRandom Array:\n", rand_arr)


Random Array:
 [[0.6101354  0.13484643]
 [0.25849431 0.12222744]]


In [13]:
sum_arr = arr1 + 10
print("\nArray + 10:", sum_arr)



Array + 10: [11 12 13 14 15]


In [ ]:
# Array slicing
print("\nFirst three elements:", arr1[:3])