In [1]:
# Exp no.: 11

In [2]:
#Aim: To perform operations on Random Forest Classifier

In [3]:
# Name: Gouri Pandey

In [4]:
# Roll no : 46

In [5]:
# sec: B

In [6]:
# subject: DSS ( Data science and statistics )

In [7]:
# Import necessary libraries
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.datasets import load_iris

In [8]:
# Step 1: Load Data
# -------------------------------
data = load_iris()  # Example dataset
X = data.data
y = data.target

# Check if data is valid
if X.size == 0 or y.size == 0:
    raise ValueError("Dataset is empty. Please provide valid input features and labels.")


In [9]:
# Step 2: Split Data
# -------------------------------
x_train, x_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)


In [10]:
# Step 3: Initialize Random Forest
# -------------------------------
rf = RandomForestClassifier(random_state=42)

# -------------------------------
# Optional: Hyperparameter Tuning
# -------------------------------
param_grid = {
    'n_estimators': [50, 100, 200],
    'criterion': ['gini', 'entropy'],
    'max_depth': [None, 5, 10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

grid_search = GridSearchCV(rf, param_grid, cv=5, scoring='accuracy', n_jobs=-1)
grid_search.fit(x_train, y_train)
best_rf = grid_search.best_estimator_
print("Best Parameters:", grid_search.best_params_)


Best Parameters: {'criterion': 'gini', 'max_depth': None, 'min_samples_leaf': 1, 'min_samples_split': 10, 'n_estimators': 50}


In [11]:
# Step 4: Fit the Best Model
# -------------------------------
best_rf.fit(x_train, y_train)


RandomForestClassifier(min_samples_split=10, n_estimators=50, random_state=42)

In [12]:
# Step 5: Predictions
# -------------------------------
y_pred5 = best_rf.predict(x_test)

In [13]:
# Step 6: Evaluation
# -------------------------------
accuracy = accuracy_score(y_test, y_pred5)
print(f"Accuracy: {accuracy:.4f}")

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred5))

print("\nClassification Report:")
print(classification_report(y_test, y_pred5))


Accuracy: 0.9667

Confusion Matrix:
[[10  0  0]
 [ 0  9  1]
 [ 0  0 10]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.90      0.95        10
           2       0.91      1.00      0.95        10

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30

